### PR TITLE
Performance tweak for w8IsSpace

### PR DESCRIPTION
**Pull request by vdukhovni**

### CODE REVIEW

**Comment by fosskers** [comment]
Good thing I checked - I was about to make a release. Note that I simplified the CHANGELOG on `master` somewhat. Your new entry can just appear under the single `Changed` header. In terms of CHANGELOG format, I've been following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

**Comment by vdukhovni** [comment]
> Good thing I checked - I was about to make a release. Note that I simplified the CHANGELOG on `master` somewhat. Your new entry can just appear under the single `Changed` header. In terms of CHANGELOG format, I've been following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

Yes, turns out I was racing you to put a finishing touch on the release as a result of the current discussion on PR 315 for bytestring. Seems this might just squeak in. Thanks!

**Comment by vdukhovni** [comment]
> Good thing I checked - I was about to make a release. Note that I simplified the CHANGELOG on `master` somewhat. Your new entry can just appear under the single `Changed` header. In terms of CHANGELOG format, I've been following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

Force pushed a version with the updated CHANGELOG style.

**Comment by vdukhovni** [comment]
By the way, Travis CI seems massively backlogged recently, it'll take a while...

**Comment by fosskers** [comment]
That's okay, the Github CI is more representative.

**Pull request merged**
